development:
  adapter: postgresql
  encoding: unicode
  database: phy_development
  pool: 5
  username: pooya
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: phy_test
  pool: 5
  username: pooya
  password: